[package]
name = "vrm-rs-wgpu-web"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[workspace]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.7"
vrm-adapter-wgpu = { path = "../../../crates/vrm-adapter-wgpu" }
vrm-io = { path = "../../../crates/vrm-io" }
wasm-bindgen = "0.2.125"
wasm-bindgen-futures = "0.4.75"
web-sys = { version = "0.3.102", features = [
    "Document",
    "Element",
    "HtmlCanvasElement",
    "Window",
    "console",
] }
