[package]
name = "vrm-io"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
gltf.workspace = true
indexmap.workspace = true
serde_json.workspace = true
serde.workspace = true
thiserror.workspace = true
vrm-core = { path = "../vrm-core" }
vrm-protocol = { path = "../vrm-protocol" }
vrm-sans-io = { path = "../vrm-sans-io" }
