[package]
name = "vrm-adapter"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[features]
bevy = []

[dependencies]
glam.workspace = true
indexmap.workspace = true
thiserror.workspace = true
vrm-core = { path = "../vrm-core" }
vrm-runtime = { path = "../vrm-runtime" }

[dev-dependencies]
vrm-io = { path = "../vrm-io" }
